mkdir C:\AmazIT\Original\priv-app
adb pull /system/priv-app/BackupRestoreConfirmation C:\AmazIT\Original\priv-app
adb pull /system/priv-app/CustomSettings            C:\AmazIT\Original\priv-app
adb pull /system/priv-app/DefaultContainerService   C:\AmazIT\Original\priv-app
adb pull /system/priv-app/ExternalStorageProvider   C:\AmazIT\Original\priv-app
adb pull /system/priv-app/FusedLocation             C:\AmazIT\Original\priv-app
adb pull /system/priv-app/HmAlarmClock              C:\AmazIT\Original\priv-app
adb pull /system/priv-app/InputDevices              C:\AmazIT\Original\priv-app
adb pull /system/priv-app/ManagedProvisioning       C:\AmazIT\Original\priv-app
adb pull /system/priv-app/MediaProvider             C:\AmazIT\Original\priv-app
adb pull /system/priv-app/OtaWatch                  C:\AmazIT\Original\priv-app
adb pull /system/priv-app/ProxyHandler              C:\AmazIT\Original\priv-app
adb pull /system/priv-app/SettingsProvider          C:\AmazIT\Original\priv-app
adb pull /system/priv-app/SharedStorageBackup       C:\AmazIT\Original\priv-app
adb pull /system/priv-app/Shell                     C:\AmazIT\Original\priv-app
adb pull /system/priv-app/SysInfo                   C:\AmazIT\Original\priv-app
adb pull /system/priv-app/SystemUI                  C:\AmazIT\Original\priv-app
adb pull /system/priv-app/TaskManager               C:\AmazIT\Original\priv-app
adb pull /system/priv-app/WearAirPlaneMode          C:\AmazIT\Original\priv-app
adb pull /system/priv-app/WearLauncher              C:\AmazIT\Original\priv-app
adb pull /system/priv-app/WearSettings              C:\AmazIT\Original\priv-app
adb pull /system/priv-app/WifiUploadData            C:\AmazIT\Original\priv-app