java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\BackupRestoreConfirmation C:\AmazIT\Src\priv-app\BackupRestoreConfirmation.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\CustomSettings            C:\AmazIT\Src\priv-app\CustomSettings.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\DefaultContainerService   C:\AmazIT\Src\priv-app\DefaultContainerService.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\ExternalStorageProvider   C:\AmazIT\Src\priv-app\ExternalStorageProvider.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\FusedLocation             C:\AmazIT\Src\priv-app\FusedLocation.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\HmAlarmClock              C:\AmazIT\Src\priv-app\HmAlarmClock.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\InputDevices              C:\AmazIT\Src\priv-app\InputDevices.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\ManagedProvisioning       C:\AmazIT\Src\priv-app\ManagedProvisioning.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\MediaProvider             C:\AmazIT\Src\priv-app\MediaProvider.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\OtaWatch                  C:\AmazIT\Src\priv-app\OtaWatch.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\ProxyHandler              C:\AmazIT\Src\priv-app\ProxyHandler.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\SettingsProvider          C:\AmazIT\Src\priv-app\SettingsProvider.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\SharedStorageBackup       C:\AmazIT\Src\priv-app\SharedStorageBackup.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\Shell                     C:\AmazIT\Src\priv-app\Shell.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\SysInfo                   C:\AmazIT\Src\priv-app\SysInfo.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\SystemUI                  C:\AmazIT\Src\priv-app\SystemUI.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\TaskManager               C:\AmazIT\Src\priv-app\TaskManager.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\WearAirPlaneMode          C:\AmazIT\Src\priv-app\WearAirPlaneMode.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\WearLauncher              C:\AmazIT\Src\priv-app\WearLauncher.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\WearSettings              C:\AmazIT\Src\priv-app\WearSettings.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\priv-app\WifiUploadData            C:\AmazIT\Src\priv-app\WifiUploadData.apk
