java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\BackupRestoreConfirmation\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\CustomSettings\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\DefaultContainerService\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\ExternalStorageProvider\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\FusedLocation\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\HmAlarmClock\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\InputDevices\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\ManagedProvisioning\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\MediaProvider\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\OtaWatch\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\ProxyHandler\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\SettingsProvider\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\SharedStorageBackup\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\Shell\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\SysInfo\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\SystemUI\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\TaskManager\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\WearAirPlaneMode\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\WearLauncher\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\WearSettings\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\priv-app\WifiUploadData\
