adb push C:\AmazIT\Traduzido\priv-app\BackupRestoreConfirmation.apk /system/priv-app/BackupRestoreConfirmation/
adb push C:\AmazIT\Traduzido\priv-app\DefaultContainerService.apk   /system/priv-app/DefaultContainerService/
adb push C:\AmazIT\Traduzido\priv-app\ExternalStorageProvider.apk   /system/priv-app/ExternalStorageProvider/
adb push C:\AmazIT\Traduzido\priv-app\FusedLocation.apk             /system/priv-app/FusedLocation/
adb push C:\AmazIT\Traduzido\priv-app\HmAlarmClock.apk              /system/priv-app/HmAlarmClock/
adb push C:\AmazIT\Traduzido\priv-app\InputDevices.apk              /system/priv-app/InputDevices/
adb push C:\AmazIT\Traduzido\priv-app\ManagedProvisioning.apk       /system/priv-app/ManagedProvisioning/
::adb push C:\AmazIT\Traduzido\priv-app\MediaProvider.apk             /system/priv-app/MediaProvider/
adb push C:\AmazIT\Traduzido\priv-app\OtaWatch.apk                  /system/priv-app/OtaWatch/
adb push C:\AmazIT\Traduzido\priv-app\ProxyHandler.apk              /system/priv-app/ProxyHandler/
adb push C:\AmazIT\Traduzido\priv-app\SettingsProvider.apk          /system/priv-app/SettingsProvider/
adb push C:\AmazIT\Traduzido\priv-app\SharedStorageBackup.apk       /system/priv-app/SharedStorageBackup/
adb push C:\AmazIT\Traduzido\priv-app\Shell.apk                     /system/priv-app/Shell/
::adb push C:\AmazIT\Traduzido\priv-app\SysInfo.apk                  /system/priv-app/SysInfo/
::adb push C:\AmazIT\Traduzido\priv-app\SystemUI.apk                  /system/priv-app/SystemUI/
::adb push C:\AmazIT\Traduzido\priv-app\TaskManager.apk                  /system/priv-app/TaskManager/
adb push C:\AmazIT\Traduzido\priv-app\WearAirPlaneMode.apk          /system/priv-app/WearAirPlaneMode/
adb push C:\AmazIT\Traduzido\priv-app\WearLauncher.apk              /system/priv-app/WearLauncher/
adb push C:\AmazIT\Traduzido\priv-app\WearSettings.apk              /system/priv-app/WearSettings/
adb push C:\AmazIT\Traduzido\priv-app\WifiUploadData.apk            /system/priv-app/WifiUploadData/
