mkdir C:\AmazIT\Original\app
adb pull /system/app/AdvertiseManager   C:\AmazIT\Original\app
adb pull /system/app/AmazfitWeather     C:\AmazIT\Original\app
adb pull /system/app/Bluetooth          C:\AmazIT\Original\app
adb pull /system/app/BluetoothProxy     C:\AmazIT\Original\app
adb pull /system/app/CaptivePortalLogin C:\AmazIT\Original\app
adb pull /system/app/CertInstaller      C:\AmazIT\Original\app
adb pull /system/app/ChargingUI         C:\AmazIT\Original\app
adb pull /system/app/HmFTP              C:\AmazIT\Original\app
adb pull /system/app/HmLab              C:\AmazIT\Original\app
adb pull /system/app/HmMediaPlayer      C:\AmazIT\Original\app
adb pull /system/app/HmVoice            C:\AmazIT\Original\app
adb pull /system/app/HuamiIME           C:\AmazIT\Original\app
adb pull /system/app/HuamiSelfTest      C:\AmazIT\Original\app
adb pull /system/app/HuamiWatchFaces    C:\AmazIT\Original\app
adb pull /system/app/KeyChain           C:\AmazIT\Original\app
adb pull /system/app/MyWatch            C:\AmazIT\Original\app
adb pull /system/app/PackageInstaller   C:\AmazIT\Original\app
adb pull /system/app/SensorList         C:\AmazIT\Original\app
adb pull /system/app/SetupWizard        C:\AmazIT\Original\app
adb pull /system/app/TrainingPlan       C:\AmazIT\Original\app
adb pull /system/app/UnlockMIUI         C:\AmazIT\Original\app
adb pull /system/app/WearBLE            C:\AmazIT\Original\app
adb pull /system/app/WearCompass        C:\AmazIT\Original\app
adb pull /system/app/WearHealth         C:\AmazIT\Original\app
adb pull /system/app/WearLogger         C:\AmazIT\Original\app
adb pull /system/app/WearSensorService  C:\AmazIT\Original\app
adb pull /system/app/WearServices       C:\AmazIT\Original\app
adb pull /system/app/WearSmartHome      C:\AmazIT\Original\app
adb pull /system/app/WearSports         C:\AmazIT\Original\app
adb pull /system/app/webview            C:\AmazIT\Original\app