java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\AdvertiseManager           C:\AmazIT\Src\app\AdvertiseManager.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\AmazfitWeather             C:\AmazIT\Src\app\AmazfitWeather.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\Bluetooth                  C:\AmazIT\Src\app\Bluetooth.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\BluetoothProxy             C:\AmazIT\Src\app\BluetoothProxy.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\CaptivePortalLogin         C:\AmazIT\Src\app\CaptivePortalLogin.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\CertInstaller              C:\AmazIT\Src\app\CertInstaller.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\ChargingUI                 C:\AmazIT\Src\app\ChargingUI.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HmFTP                      C:\AmazIT\Src\app\HmFTP.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HmLab                      C:\AmazIT\Src\app\HmLab.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HmMediaPlayer              C:\AmazIT\Src\app\HmMediaPlayer.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HmVoice                    C:\AmazIT\Src\app\HmVoice.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HuamiIME                   C:\AmazIT\Src\app\HuamiIME.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HuamiSelfTest              C:\AmazIT\Src\app\HuamiSelfTest.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\HuamiWatchFaces            C:\AmazIT\Src\app\HuamiWatchFaces.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\KeyChain                   C:\AmazIT\Src\app\KeyChain.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\MyWatch                    C:\AmazIT\Src\app\MyWatch.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\PackageInstaller           C:\AmazIT\Src\app\PackageInstaller.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\SensorList                 C:\AmazIT\Src\app\SensorList.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\SetupWizard                C:\AmazIT\Src\app\SetupWizard.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\TrainingPlan               C:\AmazIT\Src\app\TrainingPlan.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\UnlockMIUI                 C:\AmazIT\Src\app\UnlockMIUI.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearBLE                    C:\AmazIT\Src\app\WearBLE.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearCompass                C:\AmazIT\Src\app\WearCompass.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearHealth                 C:\AmazIT\Src\app\WearHealth.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearLogger                 C:\AmazIT\Src\app\WearLogger.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearSensorService          C:\AmazIT\Src\app\WearSensorService.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearServices               C:\AmazIT\Src\app\WearServices.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearSmartHome              C:\AmazIT\Src\app\WearSmartHome.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\WearSports                 C:\AmazIT\Src\app\WearSports.apk
java -jar C:\windows\apktool.jar d -f -s -o C:\AmazIT\Original\app\webview                    C:\AmazIT\Src\app\webview.apk