java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\AdvertiseManager\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\AmazfitWeather\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\Bluetooth\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\BluetoothProxy\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\CaptivePortalLogin\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\CertInstaller\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\ChargingUI\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HmFTP\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HmLab\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HmMediaPlayer\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HmVoice\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HuamiIME\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HuamiSelfTest\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\HuamiWatchFaces\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\KeyChain\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\MyWatch\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\PackageInstaller\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\SensorList\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\SetupWizard\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\TrainingPlan\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\UnlockMIUI\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearBLE\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearCompass\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearHealth\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearLogger\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearSensorService\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearServices\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearSmartHome\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\WearSports\
java -jar C:\windows\apktool.jar b -c C:\AmazIT\Src\app\webview\
