mkdir C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\AdvertiseManager\dist\*.*   C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\AmazfitWeather\dist\*.*     C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\Bluetooth\dist\*.*          C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\BluetoothProxy\dist\*.*     C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\CaptivePortalLogin\dist\*.* C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\CertInstaller\dist\*.*      C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\ChargingUI\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HmFTP\dist\*.*              C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HmLaAmazIT6\dist\*.*        C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HmMediaPlayer\dist\*.*      C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HmVoice\dist\*.*            C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HuamiIME\dist\*.*           C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HuamiSelfTest\dist\*.*      C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\HuamiWatchFaces\dist\*.*    C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\KeyChain\dist\*.*           C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\MyWatch\dist\*.*            C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\PackageInstaller\dist\*.*   C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\SensorList\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\SetupWizard\dist\*.*        C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\TrainingPlan\dist\*.*       C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\UnlockMIUI\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearBLE\dist\*.*            C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearCompass\dist\*.*        C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearHealth\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearLogger\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearSensorService\dist\*.*  C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearServices\dist\*.*       C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearSmartHome\dist\*.*      C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\WearSports\dist\*.*         C:\AmazIT\Traduzido\app
copy C:\AmazIT\Src\app\webview\dist\*.*            C:\AmazIT\Traduzido\app
