adb push C:\AmazIT\Traduzido\app\AdvertiseManager.apk         /system/app/AdvertiseManager/
adb push C:\AmazIT\Traduzido\app\AmazfitWeather.apk           /system/app/AmazfitWeather/
::adb push C:\AmazIT\Traduzido\app\Bluetooth.apk                /system/app/Bluetooth/
adb push C:\AmazIT\Traduzido\app\BluetoothProxy.apk           /system/app/BluetoothProxy/
::adb push C:\AmazIT\Traduzido\app\CaptivePortalLogin.apk       /system/app/CaptivePortalLogin/
adb push C:\AmazIT\Traduzido\app\CertInstaller.apk            /system/app/CertInstaller/
adb push C:\AmazIT\Traduzido\app\ChargingUI.apk               /system/app/ChargingUI/
adb push C:\AmazIT\Traduzido\app\HmFTP.apk                    /system/app/HmFTP/
::adb push C:\AmazIT\Traduzido\app\HmMediaPlayer.apk            /system/app/HmLab/
adb push C:\AmazIT\Traduzido\app\HmTvHelper.apk               /system/app/HmMediaPlayer/
adb push C:\AmazIT\Traduzido\app\HmVoice.apk                  /system/app/HmVoice/
adb push C:\AmazIT\Traduzido\app\HuamiIME.apk                 /system/app/HuamiIME/
adb push C:\AmazIT\Traduzido\app\HuamiSelfTest.apk            /system/app/HuamiSelfTest/
adb push C:\AmazIT\Traduzido\app\HuamiWatchFaces.apk          /system/app/HuamiWatchFaces/
adb push C:\AmazIT\Traduzido\app\KeyChain.apk                 /system/app/KeyChain/
adb push C:\AmazIT\Traduzido\app\MyWatch.apk                  /system/app/MyWatch/
::adb push C:\AmazIT\Traduzido\app\PackageInstaller.apk         /system/app/PackageInstaller/
adb push C:\AmazIT\Traduzido\app\SensorList.apk               /system/app/SensorList/
adb push C:\AmazIT\Traduzido\app\SetupWizard.apk              /system/app/SetupWizard/
adb push C:\AmazIT\Traduzido\app\TrainingPlan.apk             /system/app/TrainingPlan/
adb push C:\AmazIT\Traduzido\app\UnlockMIUI.apk               /system/app/UnlockMIUI/
adb push C:\AmazIT\Traduzido\app\WearBLE.apk                  /system/app/WearBLE/
adb push C:\AmazIT\Traduzido\app\WearCompass.apk              /system/app/WearCompass/
adb push C:\AmazIT\Traduzido\app\WearHealth.apk               /system/app/WearHealth/
adb push C:\AmazIT\Traduzido\app\WearLogger.apk               /system/app/WearLogger/
adb push C:\AmazIT\Traduzido\app\WearSensorService.apk        /system/app/WearSensorService/
adb push C:\AmazIT\Traduzido\app\WearServices.apk             /system/app/WearServices/
adb push C:\AmazIT\Traduzido\app\WearSmartHome.apk            /system/app/WearSmartHome/
adb push C:\AmazIT\Traduzido\app\WearSports.apk               /system/app/WearSports/
adb push C:\AmazIT\Traduzido\app\webview.apk                  /system/app/webview/